[[constraint]]
  name = "github.com/franela/goblin"
  revision = "74c9fe110d4bfd04c222a089a309e0a97e258534"

[[constraint]]
  name = "github.com/gorilla/mux"
  revision = "0eeaf8392f5b04950925b8a69fe70f110fa7cbfc"

[[constraint]]
  name = "github.com/onsi/gomega"
  revision = "a78ae492d53aad5a7a232d0d0462c14c400e3ee7"
